version: '3'
services:
  docker-app:
    image: nailsonnb/cooperativismo-app
    ports:
    - 8080:8080
    networks:
    - dock-network
    depends_on:
    - meubanco-mysql
    restart: always
  meubanco-mysql:
    container_name: meubanco-mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: compasso
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
    - 3306:3306
    networks:
    - dock-network
    restart: always
networks:
  dock-network:
    driver: bridge